-- Script PostgreSQL complet pour le projet de réservation de ressources.
--
-- Ce fichier crée:
-- 1) le schéma principal,
-- 2) les index,
-- 3) les triggers de cohérence métier,
-- 4) les triggers d'historisation (audit),
-- 5) les données de référence (rôles, permissions, types, états, statuts).
--
-- Les fixtures de démonstration (entreprise, utilisateurs, ressources, réservations)
-- sont volontairement placées dans un fichier séparé: Reservations.demo.fixtures.sql

BEGIN;

-- =========================
-- Tables principales
-- =========================

CREATE TABLE companies (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_companies_name UNIQUE (name)
);

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  first_name VARCHAR(120) NOT NULL,
  last_name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone_number VARCHAR(40),
  password_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_users_company_email UNIQUE (company_id, email)
);

CREATE UNIQUE INDEX uq_users_email_global ON users (LOWER(email));

CREATE TABLE roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE user_roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id INT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_user_roles UNIQUE (user_id, role_id)
);

CREATE TABLE permissions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  description TEXT,
  CONSTRAINT uq_permissions_name UNIQUE (name)
);

CREATE TABLE role_permissions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id INT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id INT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  CONSTRAINT uq_role_permissions UNIQUE (role_id, permission_id)
);

CREATE TABLE resource_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_resource_types_name UNIQUE (name)
);

CREATE TABLE resource_states (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label VARCHAR(120) NOT NULL,
  description TEXT,
  CONSTRAINT uq_resource_states_label UNIQUE (label)
);

CREATE TABLE resources (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  type_id INT NOT NULL REFERENCES resource_types(id) ON DELETE RESTRICT,
  state_id INT NOT NULL REFERENCES resource_states(id) ON DELETE RESTRICT,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(80) NOT NULL,
  location VARCHAR(255),
  capacity INT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_resources_company_code UNIQUE (company_id, code),
  CONSTRAINT chk_resources_capacity_positive CHECK (capacity IS NULL OR capacity >= 0)
);

CREATE TABLE room_details (
  resource_id INT PRIMARY KEY REFERENCES resources(id) ON DELETE CASCADE,
  building VARCHAR(255),
  floor VARCHAR(40),
  has_screen BOOLEAN NOT NULL DEFAULT FALSE,
  has_whiteboard BOOLEAN NOT NULL DEFAULT FALSE,
  has_projector BOOLEAN NOT NULL DEFAULT FALSE,
  available_places INT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_room_places_positive CHECK (available_places IS NULL OR available_places >= 0)
);

CREATE TABLE vehicle_details (
  resource_id INT PRIMARY KEY REFERENCES resources(id) ON DELETE CASCADE,
  license_plate VARCHAR(30) NOT NULL,
  brand VARCHAR(120),
  model VARCHAR(120),
  fuel_type VARCHAR(80),
  vehicle_class VARCHAR(80),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_vehicle_license_plate UNIQUE (license_plate)
);

CREATE TABLE equipment_details (
  resource_id INT PRIMARY KEY REFERENCES resources(id) ON DELETE CASCADE,
  serial_number VARCHAR(120),
  brand VARCHAR(120),
  category VARCHAR(120),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_equipment_serial_number UNIQUE (serial_number)
);

CREATE TABLE reservation_status (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(60) NOT NULL,
  label VARCHAR(120) NOT NULL,
  description TEXT,
  is_blocking BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_reservation_status_code UNIQUE (code),
  CONSTRAINT uq_reservation_status_label UNIQUE (label)
);

CREATE TABLE reservations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  resource_id INT NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  status_id INT NOT NULL REFERENCES reservation_status(id) ON DELETE RESTRICT,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NOT NULL,
  title VARCHAR(255) NOT NULL,
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_reservations_dates CHECK (end_at > start_at)
);

CREATE TABLE reservation_participants (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id INT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  user_id INT REFERENCES users(id) ON DELETE SET NULL,
  email VARCHAR(255),
  status VARCHAR(60) NOT NULL DEFAULT 'invited',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_reservation_participants_user UNIQUE (reservation_id, user_id),
  CONSTRAINT uq_reservation_participants_email UNIQUE (reservation_id, email),
  CONSTRAINT chk_reservation_participant_target CHECK (user_id IS NOT NULL OR email IS NOT NULL)
);

CREATE TABLE vehicle_usage (
  reservation_id INT PRIMARY KEY REFERENCES reservations(id) ON DELETE CASCADE,
  vehicle_id INT NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
  checked_out_at TIMESTAMP,
  returned_at TIMESTAMP,
  issue_reported_at TIMESTAMP,
  issue_description TEXT,
  issue_resolved_at TIMESTAMP,
  CONSTRAINT chk_vehicle_usage_return CHECK (returned_at IS NULL OR checked_out_at IS NOT NULL)
);
CREATE INDEX idx_vehicle_usage_vehicle ON vehicle_usage(vehicle_id);

CREATE TABLE notifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reservation_id INT REFERENCES reservations(id) ON DELETE CASCADE,
  type VARCHAR(80) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  sent_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE audit_logs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INT REFERENCES companies(id) ON DELETE SET NULL,
  user_id INT REFERENCES users(id) ON DELETE SET NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id INT,
  action VARCHAR(120) NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE maintenance_events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id INT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
  created_by_user_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_maintenance_dates CHECK (end_at > start_at)
);

-- =========================
-- Index
-- =========================

CREATE INDEX idx_users_company ON users(company_id);
CREATE INDEX idx_resources_company_type_state ON resources(company_id, type_id, state_id);
CREATE INDEX idx_reservations_resource_range ON reservations(resource_id, start_at, end_at);
CREATE INDEX idx_reservations_company_start ON reservations(company_id, start_at);
CREATE INDEX idx_reservations_user_start ON reservations(user_id, start_at);
CREATE INDEX idx_notifications_user_read_sent ON notifications(user_id, is_read, sent_at);
CREATE INDEX idx_maintenance_resource_range ON maintenance_events(resource_id, start_at, end_at);
CREATE INDEX idx_audit_company_created ON audit_logs(company_id, created_at);

-- =========================
-- Triggers techniques et métier
-- =========================

CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_companies_updated_at
BEFORE UPDATE ON companies
FOR EACH ROW
EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_resources_updated_at
BEFORE UPDATE ON resources
FOR EACH ROW
EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_reservations_updated_at
BEFORE UPDATE ON reservations
FOR EACH ROW
EXECUTE FUNCTION fn_set_updated_at();

-- Cohérence multi-entreprise: la réservation doit rester dans la même entreprise
CREATE OR REPLACE FUNCTION fn_check_reservation_company_consistency()
RETURNS TRIGGER AS $$
DECLARE
  v_user_company_id INT;
  v_resource_company_id INT;
BEGIN
  SELECT company_id INTO v_user_company_id FROM users WHERE id = NEW.user_id;
  IF v_user_company_id IS NULL THEN
    RAISE EXCEPTION 'Utilisateur % introuvable', NEW.user_id;
  END IF;

  SELECT company_id INTO v_resource_company_id FROM resources WHERE id = NEW.resource_id;
  IF v_resource_company_id IS NULL THEN
    RAISE EXCEPTION 'Ressource % introuvable', NEW.resource_id;
  END IF;

  IF NEW.company_id <> v_user_company_id OR NEW.company_id <> v_resource_company_id THEN
    RAISE EXCEPTION 'Incohérence entreprise: réservation(%) user(%) ressource(%)', NEW.company_id, v_user_company_id, v_resource_company_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reservation_company_consistency
BEFORE INSERT OR UPDATE OF company_id, user_id, resource_id ON reservations
FOR EACH ROW
EXECUTE FUNCTION fn_check_reservation_company_consistency();

-- Empêche les chevauchements sur une même ressource pour les statuts bloquants.
-- Le format '[)' signifie: début inclus, fin exclue.
-- Deux réservations adjacentes (ex: 10:00-11:00 et 11:00-12:00) ne sont pas en conflit.
CREATE OR REPLACE FUNCTION fn_prevent_reservation_overlap()
RETURNS TRIGGER AS $$
DECLARE
  v_is_blocking BOOLEAN;
BEGIN
  SELECT is_blocking INTO v_is_blocking
  FROM reservation_status
  WHERE id = NEW.status_id;

  IF COALESCE(v_is_blocking, FALSE) = FALSE THEN
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM reservations r
    JOIN reservation_status rs ON rs.id = r.status_id
    WHERE r.resource_id = NEW.resource_id
      AND r.id <> COALESCE(NEW.id, -1)
      AND rs.is_blocking = TRUE
      AND tsrange(r.start_at, r.end_at, '[)') && tsrange(NEW.start_at, NEW.end_at, '[)')
  ) THEN
    RAISE EXCEPTION 'Conflit de réservation: chevauchement détecté pour la ressource %', NEW.resource_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM maintenance_events m
    WHERE m.resource_id = NEW.resource_id
      AND tsrange(m.start_at, m.end_at, '[)') && tsrange(NEW.start_at, NEW.end_at, '[)')
  ) THEN
    RAISE EXCEPTION 'Ressource % indisponible: créneau en maintenance', NEW.resource_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reservation_no_overlap
BEFORE INSERT OR UPDATE OF resource_id, start_at, end_at, status_id ON reservations
FOR EACH ROW
EXECUTE FUNCTION fn_prevent_reservation_overlap();

-- Empêche de planifier une maintenance qui chevauche des réservations bloquantes.
CREATE OR REPLACE FUNCTION fn_prevent_maintenance_overlap()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM reservations r
    JOIN reservation_status rs ON rs.id = r.status_id
    WHERE r.resource_id = NEW.resource_id
      AND rs.is_blocking = TRUE
      AND tsrange(r.start_at, r.end_at, '[)') && tsrange(NEW.start_at, NEW.end_at, '[)')
  ) THEN
    RAISE EXCEPTION 'Maintenance impossible: conflit avec des réservations actives sur la ressource %', NEW.resource_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_maintenance_no_overlap
BEFORE INSERT OR UPDATE OF resource_id, start_at, end_at ON maintenance_events
FOR EACH ROW
EXECUTE FUNCTION fn_prevent_maintenance_overlap();

-- =========================
-- Historisation (audit)
-- =========================

-- Récupère l'utilisateur applicatif courant si l'application définit:
--   SET app.current_user_id = '123';
-- Sinon, retourne NULL.
CREATE OR REPLACE FUNCTION fn_current_actor_user_id()
RETURNS INT AS $$
DECLARE
  v_value TEXT;
BEGIN
  v_value := current_setting('app.current_user_id', TRUE);
  IF v_value IS NULL OR v_value = '' THEN
    RETURN NULL;
  END IF;
  RETURN v_value::INT;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Historise les opérations INSERT/UPDATE/DELETE dans audit_logs.
-- p_entity_type: nom métier de l'entité (reservation, resource, maintenance, etc.)
-- p_company_expr: expression SQL qui renvoie company_id à partir de NEW/OLD.
CREATE OR REPLACE FUNCTION fn_audit_change()
RETURNS TRIGGER AS $$
DECLARE
  v_entity_type TEXT;
  v_company_id INT;
  v_entity_id INT;
  v_action TEXT;
  v_details JSONB;
BEGIN
  v_entity_type := TG_ARGV[0];
  v_company_id := NULL;
  v_entity_id := NULL;

  IF TG_OP = 'INSERT' THEN
    v_action := 'insert';
    v_details := jsonb_build_object('new', to_jsonb(NEW));
    v_entity_id := NEW.id;
  ELSIF TG_OP = 'UPDATE' THEN
    v_action := 'update';
    v_details := jsonb_build_object('old', to_jsonb(OLD), 'new', to_jsonb(NEW));
    v_entity_id := COALESCE(NEW.id, OLD.id);
  ELSE
    v_action := 'delete';
    v_details := jsonb_build_object('old', to_jsonb(OLD));
    v_entity_id := OLD.id;
  END IF;

  -- Résolution du company_id selon la table source.
  IF TG_TABLE_NAME = 'companies' THEN
    v_company_id := COALESCE(NEW.id, OLD.id);
  ELSIF TG_TABLE_NAME = 'users' THEN
    v_company_id := COALESCE(NEW.company_id, OLD.company_id);
  ELSIF TG_TABLE_NAME = 'resources' THEN
    v_company_id := COALESCE(NEW.company_id, OLD.company_id);
  ELSIF TG_TABLE_NAME = 'reservations' THEN
    v_company_id := COALESCE(NEW.company_id, OLD.company_id);
  ELSIF TG_TABLE_NAME = 'maintenance_events' THEN
    SELECT r.company_id
      INTO v_company_id
    FROM resources r
    WHERE r.id = COALESCE(NEW.resource_id, OLD.resource_id);
  ELSIF TG_TABLE_NAME = 'notifications' THEN
    SELECT u.company_id
      INTO v_company_id
    FROM users u
    WHERE u.id = COALESCE(NEW.user_id, OLD.user_id);
  END IF;

  INSERT INTO audit_logs (company_id, user_id, entity_type, entity_id, action, details, created_at)
  VALUES (
    v_company_id,
    fn_current_actor_user_id(),
    COALESCE(v_entity_type, TG_TABLE_NAME),
    v_entity_id,
    v_action,
    v_details,
    NOW()
  );

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Historisation des tables métier les plus importantes.
CREATE TRIGGER trg_audit_resources
AFTER INSERT OR UPDATE OR DELETE ON resources
FOR EACH ROW
EXECUTE FUNCTION fn_audit_change('resource');

CREATE TRIGGER trg_audit_reservations
AFTER INSERT OR UPDATE OR DELETE ON reservations
FOR EACH ROW
EXECUTE FUNCTION fn_audit_change('reservation');

CREATE TRIGGER trg_audit_maintenance_events
AFTER INSERT OR UPDATE OR DELETE ON maintenance_events
FOR EACH ROW
EXECUTE FUNCTION fn_audit_change('maintenance_event');

CREATE TRIGGER trg_audit_notifications
AFTER INSERT OR UPDATE OR DELETE ON notifications
FOR EACH ROW
EXECUTE FUNCTION fn_audit_change('notification');

-- =========================
-- Fixtures de référence
-- =========================

INSERT INTO roles (name, description)
VALUES
  ('employe', 'Utilisateur standard qui réserve des ressources'),
  ('gestionnaire', 'Supervise les réservations de son périmètre'),
  ('administrateur', 'Gère utilisateurs, ressources et paramètres')
ON CONFLICT (name) DO NOTHING;

INSERT INTO permissions (name, description)
VALUES
  ('reservation.create', 'Créer une réservation'),
  ('reservation.update', 'Modifier une réservation'),
  ('reservation.cancel', 'Annuler une réservation'),
  ('resource.manage', 'Gérer les ressources'),
  ('user.manage', 'Gérer les utilisateurs'),
  ('planning.read', 'Consulter le calendrier'),
  ('audit.read', 'Consulter les journaux d''audit')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN ('reservation.create', 'reservation.update', 'reservation.cancel', 'planning.read')
WHERE r.name = 'employe'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN ('reservation.create', 'reservation.update', 'reservation.cancel', 'planning.read', 'audit.read')
WHERE r.name = 'gestionnaire'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN ('reservation.create', 'reservation.update', 'reservation.cancel', 'resource.manage', 'user.manage', 'planning.read', 'audit.read')
WHERE r.name = 'administrateur'
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO resource_types (name, description)
VALUES
  ('salle', 'Salle de réunion ou de formation'),
  ('vehicule', 'Véhicule de service'),
  ('equipement', 'Matériel partagé: étiqueteuse, microphone, caméra, etc.'),
  ('portable', 'Ordinateur portable partagé'),
  ('audiovisuel', 'Vidéoprojecteur et matériel audiovisuel')
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

INSERT INTO resource_states (label, description)
VALUES
  ('disponible', 'Ressource disponible pour réservation'),
  ('reserve', 'Ressource en cours de réservation'),
  ('indisponible', 'Ressource temporairement indisponible'),
  ('maintenance', 'Ressource en maintenance')
ON CONFLICT (label) DO NOTHING;

INSERT INTO reservation_status (code, label, description, is_blocking)
VALUES
  ('pending', 'En attente', 'Demande de réservation en attente de validation', TRUE),
  ('confirmed', 'Confirmée', 'Réservation validée', TRUE),
  ('rejected', 'Refusée', 'Réservation refusée', FALSE),
  ('cancelled', 'Annulée', 'Réservation annulée', FALSE),
  ('completed', 'Terminée', 'Réservation terminée', FALSE)
ON CONFLICT (code) DO NOTHING;

COMMIT;
